### PR TITLE
make rasmlib compatible with current version of xarray

### PR DESCRIPTION
**Pull request by dgergel**
This PR updates `xray` to `xarray` in rasmlib.

### CODE REVIEW

**Comment by dgergel** [comment]
cc @jhamman for review

**Comment by jhamman** [comment]
Cool. Happy to merge. 

@bartnijssen and @dgergel - should we move this repo to UW-Hydro?

**Comment by jhamman** [comment]
@dgergel - its up to you if you want to continue using Travis to run the tests. I suspect things will need some freshening up, given that I see Python 2.6 and 3.3 in the matrix.

**Comment by dgergel** [comment]
Seems like if we move this to UW-Hydro, which seems like a good thing to do, we would probably want to keep using Travis. Shouldn't be too difficult to make that happen, right?

**Comment by jhamman** [comment]
The two aren't directly related but its really up to you. I wouldn't think it will require much work to get the tests passing again.

**Comment by dgergel** [comment]
I'd prefer to keep using Travis testing because I like having it catch small issues before having to hunt them down the line. I'll look into what needs to be changed.

**Comment by dgergel** [comment]
@jhamman and @bartnijssen is there any point in continuing to support any versions of Python 2, or do you think we can just switch entirely to Python 3? I'm looking into fixing this now.

**Comment by jhamman** [comment]
I don't see a reason to continue supporting python 2. Xarray will drop support in a few months, as will a number of other packages.  Moreover, this package has a user community of 1, maybe 2, so we don't have to get too carried away 😄

**Comment by dgergel** [comment]
Maybe we can do what we currently do in RVIC, support the following: 

```  
 - python: 2.7
 - python: 3.4
 - python: 3.5
 - python: 3.6
```

**Comment by dgergel** [comment]
@jhamman - I know. I've just never modified travis tests before and this will be used by future RASM developers so I'm trying to make a reasonable decision. I'll go with supporting python versions 3.4-3.6

**Comment by jhamman** [comment]
Just do 3.6. Xarray is going to drop 3.4 and 3.5 soon too.

Joe Hamman
Post-Doctoral Fellow
Research Applications Laboratory
Hydrometeorological Applications Program
National Center for Atmospheric Research
Phone: 206-498-5497
Email:  jhamman@ucar.edu
Web:  joehamman.com

**Comment by dgergel** [comment]
@jhamman I removed one of the test scripts, so now the travis tests are simply testing that the build was successful and that rasmlib is installed correctly. Including the second test that I took out was causing errors and I don't think it's worth putting more time into this right now.

**Comment by dgergel** [comment]
@jhamman can you go ahead and merge this? I have some additional updates in the pipeline...

**Pull request merged**
